### ISSUE TITLE
bug in libsurv/datasets/base.py

### ISSUE THREAD

**Issue by bratitch** [liupei101/libsurv#2]
There is a bug in libsurv/datasets/base.py, function survival_stats. From this function, plot_km_survf(data, t_col="t", e_col="e") is called with hardcoded column names "t" and "e" instead of passing parameter values provided to survival_stats.

**Comment by liupei101** [comment]
Thanks for your observation. [Commit](https://github.com/liupei101/libsurv/commit/4387ed704ccc002847548d9e5bd41acc19c4f14c) has been pushed to solve it.

We will add more testing and documentation in the next few months.
