### ISSUE TITLE
请问deepcox中如何输出特征重要性

### ISSUE THREAD

**Issue by Yif18** [liupei101/libsurv#5]
您好，请问，如果我想要知道各个特征的重要程度，是否可以实现，如何输出，谢谢

**Comment by liupei101** [comment]
Hi, Yif18!
Thanks for your attention. As described in [README](https://github.com/liupei101/libsurv/blob/master/README.md), DeepCox module was merged into the libsurv package from [TFDeepSurv](https://github.com/liupei101/TFDeepSurv). Therefore, if you would like to utilize DeepCox, it is suggested referring to [TFDeepSurv](https://github.com/liupei101/TFDeepSurv) for more details.

Variable importance evaluation has ever been implemented in the branch [archive_v1](https://github.com/liupei101/TFDeepSurv/blob/archive_v1/). You can refer to [here](https://github.com/liupei101/TFDeepSurv/blob/archive_v1/tfdeepsurv/dsl.py#L509) for its implementation. The method we used was proposed by Garson, and the paper is `G. D. Garson, “Interpreting neural network connection weights,” Artificial Intelligence Expert, vol. 6, no. 4, pp. 46–51, Apr. 1991.` As the neural network is not good at model interpretability, effective approaches about the variable importance evaluation are indeed rarely seen. 

By the way, the latest version and future version of DeepCox or TFDeepSurv will not implement the variable importance evaluation as we got bad results on the simulated dataset.

**Comment by Yif18** [comment]
Thanks for your help
