### ISSUE TITLE
如何安装libsurv

### ISSUE THREAD

**Issue by Yif18** [liupei101/libsurv#7]
老师您好
使用pip install libsurv安装
出现报错
ERROR: Could not find a version that satisfies the requirement libsurv (from versions: none)
ERROR: No matching distribution found for libsurv
如何才能安装libsurv呢，恳请较为详细的指导，万分感谢

**Comment by liupei101** [comment]
Since `libsurv` is not distributed on pip, it can not be installed via pip tools, but you can download or clone this repo and then install it.

please refer to https://github.com/liupei101/libsurv#installation

**Comment by liupei101** [comment]
Install requirements have been updated and some bugs have been fixed in the current version. You can download it from [here](https://github.com/liupei101/libsurv/archive/v1.1.1.zip), and then reinstall it.
